apiVersion: v1
kind: Service
metadata:
  name: redis-store  # This matches the host name in your Python code!
spec:
  selector:
    app: redis-store # Connects to Pods with this label
  ports:
    - protocol: TCP
      port: 6379      # Port visible inside the cluster
      targetPort: 6379 # Port open on the container